language: node_js
node_js:
- '7'
cache:
  directories:
  - node_modules
branches:
  only:
  - master
install:
- yarn install
script:
- gulp svg
- gulp build__static
after_success:
- bash ./deploy.sh
env:
  global:
    secure: ueS78dyJ+F59tpPZIrQUv/5iorAC26vYItdR6U01SlUzNm/iw5wfzbGauJvrGuKaurmRj9RGnlI8DFB7TerK5Hnlc6hzaT+Xlc/gNsvxvvvnLEoU0kgQhf+jNULwnDjPJsYMRESXSSr06TLQ3IEMMSVANBnKgbXZktK0J1XARZvEpfPZU5BaGgfGuCxujW7YPAKaFHg1rvI2jcXLp9h084thm179cSSGsX20k5aiVaz/v6i/g5DpNy3OJcsrDn8tUy7V4EwPoVxsBP+J3YgKraYeut5PAPf1aYsUbR4PqzJbBB6LjX9mDjtHCDJ+tsLx/RIRMz8SfP1oh3R6OAdlM4Hzf4b+S2vDnMTgf3+37TBx43dQhcxCq327FnkmNL4Lw6CyWsuW5sjtvQ66AIEQDTFHxqIW5Ad+/DRAirK2l6el50ml/nMg+xYTPgarJb6y1J5kvtj2c13RdVWrjxFSLydxIcwcfUVdkk6CTtLy/s9Y9FGvuygEVb8sy5YIcnNMPuB0gpS6ME1xo1CopgIRmDafVqvuziEf2Yn3d7IamGwfvB+fEwkXcvqkJLHsHyRnr5XoLtLFWmIvErjyLONYBSs1UjVeaiJ+TmPx6zCar6TuZ3XByrGM+s9gJtIZx0kRZ24LTVkIvzlbHaiKlc1Fip1aBbL4kapfN9406Xw6Q8A=
