language: node_js
node_js:
- '7'
install:
- yarn install
script:
- gulp svg
- gulp build__static
deploy:
  provider: pages
  skip_cleanup: true
  on:
    branch: master
env:
  global:
  - secure: fyCmZTETbWZxBAEyXHyWhcx+0zYydD6pgz6ySV8Pl/AbNsqpONWCIX1v9+MNOkk0ZaMzCEy122/UfnxDhohhs70EVXodFdvDgIgwGBOND3DQEWI1X4QeeYgFWwx1DB7W00LjNVccv0X/8bIzF5KOzjgCw6LC3NC8h/2/QkVuR5xefZqFjWlz+6xC8ukkZlydyoXplSw8fSXC3Ttbh6T7Ve8hyvn4vl4ktxySNw1kdGGX8M8d5CqbcA3HkBcJhPTszfwFvMPFbTeHHkhG3Ns2DkFCAfAd2qfIXh9C94nqmvlwsH56BbluLyn76mYPFEtGSQh0dhLyXqmz5nCm3l0ilKZ2xReriebpjH3sYLLanAw5AF1kqNLd3btqbRR3UEFW/KllbCywg1ZhQA8iDSxd/UV0Gx3ajYsVqaUnrBceiCHjJfzp/UUKG3wVc42U0d1UczOnrD7k9TtjaiOhZlrLN4SS9/T9/AIjfidYDlOA5ROVHutqd+LqedPfgOd2jzZb/dqqT7ANw3U2GH2ilv3RfYhKGu0sHMxfOsNp006YGlEHiOMdclX7u/q8J4VGm+Njs7e4aUl05KhqLiVQ+hH/Pa9fSVmUticuECm2Ls3f5X4yae7SiqOJsmrd8BWk4Mriv9ghEJ96emyqy0/ZNbMqrKveopikFDIfcHwyLFafuNg=
