language: node_js
node_js:
- '7'
install:
- yarn install
script:
- gulp svg
- gulp build__static
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  on:
    branch: master
env:
  global:
  - secure: hGp4ekYtFJ3T3QuXl+L5sUmxcB3QeqFKD9muAjiEGTYvexSeipvL47HEwig4w+tFuetWBhjzc2V/6QK5xpbCvQmW5DdD3TplraNK7OtaTsLTiwFu6olQP0C6n2RxZyaCSazIQ31Fd3/LXyvwq+hk7nO/Wkir8RLaX8HI1wD0utoV1s8FdavZP1n8xc+AkAgBjCLgySN7dT+F9XZExqAOsPLppvM4ehpNHJYrw+78QJ/hLpOMfkKDMQbJdqrsjMra107c5ViMiiEwqwldA1mk+Cx747yxkXUPsIYebLDqdUCl610B8PKH6EYwThV7Jw8YDMm4VOum7CTZT8PX6kREwUdGYyOryvqTntqmcrRYc+HtHWLFk9yw/fZnPMDJ5wx7d4qvPEsJMPSDVETQMFTOo5/9MJRgitPOMK5KU9JoRwlYRr1jhwjCg6m/N2Nyi41cs0I5jn2iL2CLF82xt/TUsa51EH+E41rBaUmFibrWT5zABIaJDCF5l8h02FNNPJjAUPLAhHTByXpYk6+zh4ZV8k/lRS/JFgQ+dShOIbvweVkaufEK4tolV4K8Tcd9YYPysvdCXQAxGPm1F83UuFDOJrcAxd9DWal0ePapiBM+Wdkj8a2Bhzaq7Wtbo8CYcHyuv1jcj0OnyVj/j8Jvrq5CbQ9HRh0/5IQl8QLIh7gphJo=
