language: node_js
node_js:
- '7'
cache:
  directories:
  - node_modules
branches:
  only:
  - master

before_install:
- openssl aes-256-cbc -K $encrypted_722ef1dc8c96_key -iv $encrypted_722ef1dc8c96_iv -in publish-key.enc -out ~/.ssh/publish-key -d
- chmod u=rw,og= ~/.ssh/publish-key
- echo "Host github.com" >> ~/.ssh/config
- echo "  IdentityFile ~/.ssh/publish-key" >> ~/.ssh/config
- git --version
- git remote set-url origin git@github.com:github-coder/capti-website.git
- git fetch origin -f gh-pages:gh-pages

install:
- yarn install
script:
- gulp svg
- gulp build__static
after_success:
- ghp-import -n -p -m "Update gh-pages." docs
